### PR TITLE
Added React router to create routing

### LINKED ISSUE #5: Add routing using react-router package

### PR DESCRIPTION
**Pull request by lwandokasuba**
Closes #5

### CODE REVIEW

**Comment by IttaiTumelo** [comment]
Oh, style script🫠, this learning will be learning. Looking forward. I have looked at everything, I am just wondering when the auto deploy will start working. I am new at reviewing code. I am about to clone the project so that I can see this from code.

**Comment by lwandokasuba** [comment]
@IttaiTumelo I'll try to see exactly why it's not working on pull request

**Comment by IttaiTumelo** [comment]
Cool!

**Comment by lwandokasuba** [comment]
@IttaiTumelo You can review here on the website

**Comment by lwandokasuba** [comment]
@IttaiTumelo I've set branch protection to only merge when atleast one person reviews

**Comment by IttaiTumelo** [comment]
> @IttaiTumelo I've set branch protection to only merge when atleast one person reviews

Now I understand...

**Comment by lwandokasuba** [comment]
@everyone fixed the preview deploy action

**Review by mwala-zm — APPROVED** [review]
Looks good to me

**Comment by IttaiTumelo** [comment]
Awesome 😎

**Comment by lwandokasuba** [comment]
Thanks Hanzo

**Pull request merged**
